# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b99bd67103284c4fad7727be3bfb03ac9bd0389c867135f923d375eccb6cb19071183644a229c50fd01316f53b39a415c9f5b450eb1b0c1d0e69176424dd4f85

test:
  secret_key_base: b5df59869e64f93fa36f74ac6ad542ba9923af11eaf027edfadb5c61bb59ff7c62c7f77b1a034652b1205a4c6f94ca6f4d607b82a4bccd079cdc6d5221fedf70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
